name: Environment setup

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: snu-cv-project
    - name: Testing ls
      run: |
        ls -la
#     - name: Bash
#       shell: bash
#       run: ls
