name: Environment setup

on: [push]

jobs:
  setup-linux-env:
    runs-on: ubuntu-latest

    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        activate-environment: snu-cv-project
    - uses: actions/checkout@v2
    - name: Python Requirements and Detector
      run: |
        ls -la
        pip install -r ./ml/detection/requirements.txt
        python ./ml/detection/main.py ./ml/detection/data/action_video_test.mov
